# Generated by Django 5.2.9 on 2025-12-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_first_name", models.CharField(max_length=100)),
                ("student_last_name", models.CharField(max_length=100)),
                ("student_age", models.IntegerField()),
                ("student_address", models.CharField(max_length=255)),
                ("student_birthday", models.DateField()),
                ("student_gpa", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["student_first_name"],
            },
        ),
    ]
